# .streamlit/config.toml
[theme]
base="dark"         
primaryColor="darkMagenta"  # buttons/accents
textColor = "white"
linkColor = "plum"
font="sans-serif"
codeFont = "monospace"

[theme.sidebar]
primaryColor = "purple"
