# .streamlit/config.toml
[theme]
base="light"         
primaryColor="darkmagenta"  # buttons/accents
textColor = "black"
linkColor = "orchid"
backgroundColor = "floralwhite"
secondaryBackgroundColor="antiquewhite"
font="sans-serif"
codeFont = "monospace"

[theme.sidebar]
primaryColor = "darkmagenta"
backgroundColor = "thistle"
