# .streamlit/config.toml
[theme]
base="light"         
primaryColor="darkmagenta"  # buttons/accents
textColor = "black"
linkColor = "orchid"
linkUnderline = "purple"
backgroundColor = "snow"
secondaryBackgroundColor="linen"
font="sans-serif"
codeFont = "monospace"

[theme.sidebar]
primaryColor = "purple"
backgroundColor = "floralwhite"
