# .streamlit/config.toml
[theme]
base="light"         
primaryColor="darkmagenta"  # buttons/accents
textColor = "black"
linkColor = "orchid"
linkUnderline = "purple"
backgroundColor = "ivory"
secondaryBackgroundColor="linen"
font="sans-serif"
codeFont = "monospace"

[theme.sidebar]
textColor = "white"
primaryColor = "plum"
backgroundColor = "purple"
secondaryBackgroundColor = "darkmagenta"
